HELP_DICT = {
    "tel_name": "Telescope name",
    "source_ra": "Right Ascension of the source",
    "source_dec": "Declination of the source",
    "f0": "Starting frequency",
    "df": "Frequency step size",
    "nchan": "Number of frequency channels",
    "t_int": "Integration time",
    "start_ha": "Start hour angle",
    "end_ha": "End hour angle",
    "add_noise": "Add noise to the simulation",
    "ms_name": "Name of the measurement set",
    "fitsfile_name": "Name of the fits file",
    "newRA": "New RA for the model",
    "newDEC": "New DEC for the model",
    "rephase_real": "Rephase real data",
    "reposition_model": "Reposition the model",
    "scale": "Scale for the image",
    "xpix": "X pixel size",
    "ypix": "Y pixel size",
    "system": "System to use for the simulation",
    "image_timestep": "Time step for the image",
    "xresolution": "X resolution for the image",
    "yresolution": "Y resolution for the image",
    "kappa": "Kappa value for the image",
    "theta": "Theta value for the image",
    "gamma": "Gamma value for the image",
    "disance_in_pc": "Distance in parsecs",
    "alpha": "Alpha value for the image",
    "P_sim": "P value for the simulation",
    "L_sim": "L value for the simulation",
    "nu_observed": "Observed frequency",
    "eta": "Eta value for the image",
    "dtype": "Type of data",
    "load_interp": "Load interpolation data",
    "container_name": "Name of the container for running the simulation",
    "container_type": "Type of container to use (e.g., 'singularity', 'docker', or 'none')",
}

TYPES_DICT = {
    "tel_name": str,
    "source_ra": str,
    "source_dec": str,
    "f0": str,
    "df": str,
    "nchan": int,
    "t_int": str,
    "start_ha": str,
    "end_ha": str,
    "add_noise": bool,
    "ms_name": str,
    "fitsfile_name": str,
    "newRA": str,
    "newDEC": str,
    "rephase_real": bool,
    "reposition_model": bool,
    "scale": str,
    "xpix": str,
    "ypix": str,
    "system": str,
    "image_timestep": int,
    "xresolution": float,
    "yresolution": float,
    "kappa": float,
    "theta": float,
    "gamma": float,
    "distance_in_pc": int,
    "alpha": float,
    "P_sim": float,
    "L_sim": float,
    "nu_observe": float,
    "eta": float,
    "dtype": str,
    "load_interp": bool
}