add_noise: true
container_name: blobrender-local.sif
container_type: singularity
fitsfile_name: fits_maxij1820_simulation_53_1.51GHz.fits
image_timestep: 14
ms_name: my_emerlin_sim_53.ms
newDEC: 7.18675
newRA: -84.90825
rephase_real: true
reposition_model: true
scale: 0.003764
telescopename: e-MERLIN
xpix: 1300
ypix: 1300
